# Generated by Django 3.2.7 on 2021-09-26 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JakmallScrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0, verbose_name='Price (normal)')),
                ('final_price', models.IntegerField(default=0, verbose_name='Price (after discount cut)')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount (in %)')),
                ('stock', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0, verbose_name='Price (in Gram)')),
                ('variant', models.CharField(blank=True, max_length=551)),
                ('url', models.URLField(max_length=512)),
                ('seller', models.CharField(max_length=255)),
                ('seller_url', models.URLField(max_length=512)),
                ('seller_location', models.CharField(blank=True, max_length=512)),
                ('rating_count', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JakmallImagesScrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='images/jackmall/temp/')),
                ('url', models.URLField(max_length=512)),
                ('image_type', models.IntegerField(choices=[(1, 'Standard'), (2, 'Thumbnail'), (3, 'Square')], default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('jakmall_scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.jakmallscrapper')),
            ],
        ),
    ]
