# Generated by Django 3.2.7 on 2021-09-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jakmallscrapper',
            name='sold_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jakmallscrapper',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
